=== swaits/glicko2/py/xmlrate.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="ratingtype">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="100.0"/>
        <xs:maxInclusive value="4000.0"/>
    </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="deviationtype">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="700.0"/>
    </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="volatilitytype">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="10.0"/>
    </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="nametype">
    <xs:restriction base="xs:string">
        <xs:whiteSpace value="collapse"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="commenttype">
    <xs:restriction base="xs:string">
        <xs:whiteSpace value="preserve"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="resulttype">
    <xs:restriction base ="xs:string">
        <xs:enumeration value="win"/>
        <xs:enumeration value="loss"/>
        <xs:enumeration value="draw"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="racetype">
    <xs:choice>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="competitor" type="nametype"/>
    </xs:choice>
</xs:complexType>

<xs:complexType name="gametype">
    <xs:all>
        <xs:element minOccurs="1" name="home" type="nametype"/>
        <xs:element minOccurs="1" name="away" type="nametype"/>
        <xs:element minOccurs="1" name="result" type="resulttype"/>
        <xs:element minOccurs="0" name="comment" type="commenttype"/>        
    </xs:all>
</xs:complexType>

<xs:complexType name="periodtype">
    <xs:choice>
        <xs:element maxOccurs="unbounded" name="game" type="gametype"/>
        <xs:element maxOccurs="unbounded" name="race" type="racetype"/>
    </xs:choice>
</xs:complexType>

<xs:complexType name="teamtype">
    <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" name="name" type="nametype"/>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="member" type="nametype"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="playertype">
    <xs:all>
        <xs:element minOccurs="1" name="name" type="nametype"/>
        <xs:element minOccurs="0" name="rating" type="ratingtype"/>
        <xs:element minOccurs="0" name="deviation" type="deviationtype"/>
        <xs:element minOccurs="0" name="volatility" type="volatilitytype"/>
    </xs:all>
</xs:complexType>

<xs:complexType name="ratingdoctype">
    <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="player" type="playertype"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="team" type="teamtype"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="period" type="periodtype"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="ratingdoc" type="ratingdoctype"/>

</xs:schema>

=== swaits/glicko2/py/data/hockey-2.xml
<?xml version="1.0" encoding="UTF-8"?>

<ratingdoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.waits.net/XML/xmlrate.xsd">

    <player>
        <name>penguins</name>
				<rating>1458.9</rating>
				<deviation>145.9</deviation>
				<variance>0.06</variance>
    </player>

    <player>
        <name>no ties</name>
				<rating>1474.4</rating>
				<deviation>141.2</deviation>
				<variance>0.06</variance>
    </player>

    <player>
        <name>zzyzzx</name>
				<rating>1747.3</rating>
				<deviation>146.8</deviation>
				<variance>0.06</variance>
    </player>

    <player>
        <name>spitfires</name>
				<rating>1688.8</rating>
				<deviation>152.5</deviation>
				<variance>0.06</variance>
    </player>

    <player>
        <name>space monkeys</name>
				<rating>1666.4</rating>
				<deviation>132.5</deviation>
				<variance>0.06</variance>
    </player>

    <player>
        <name>plug uglys</name>
				<rating>1247.4</rating>
				<deviation>149.5</deviation>
				<variance>0.06</variance>
    </player>

    <player>
        <name>shockers</name>
				<rating>1117.6</rating>
				<deviation>162.1</deviation>
				<variance>0.06</variance>
    </player>

    <player>
        <name>phantoms</name>
				<rating>1527.9</rating>
				<deviation>134.9</deviation>
				<variance>0.06</variance>
    </player>

    <player>
        <name>buk hockey</name>
    </player>

    <player>
        <name>battle apples</name>
    </player>


		<!-- 9/20/2004 -->
    <period>
        <game> <!-- no line -->
            <home>shockers</home>
            <away>plug uglys</away>
            <result>win</result>
        </game>

        <game> <!-- spitfires over penguins -->
            <home>spitfires</home>
            <away>penguins</away>
            <result>win</result>
        </game>

        <game> <!-- zzyzzx over space monkeys -->
            <home>zzyzzx</home>
            <away>space monkeys</away>
            <result>win</result>
        </game>

        <game> <!-- no line -->
            <home>no ties</home>
            <away>buk hockey</away>
            <result>loss</result>
        </game>
    </period>

		<!-- 9/27/2004 -->
    <period>
        <game>
            <home>buk hockey</home>
            <away>space monkeys</away>
            <result>draw</result>
        </game>

        <game>
            <home>spitfires</home>
            <away>zzyzzx</away>
            <result>win</result>
        </game>

        <game>
            <home>plug uglys</home>
            <away>phantoms</away>
            <result>loss</result>
        </game>

        <game>
            <home>shockers</home>
            <away>no ties</away>
            <result>loss</result>
        </game>

        <game>
            <home>penguins</home>
            <away>battle apples</away>
            <result>win</result>
        </game>
    </period>

		<!-- 10/04/2004 -->
    <period>
        <game>
            <home>buk hockey</home>
            <away>spitfires</away>
            <result>loss</result>
        </game>

        <game>
            <home>plug uglys</home>
            <away>no ties</away>
            <result>loss</result>
        </game>

        <game>
            <home>space monkeys</home>
            <away>shockers</away>
            <result>win</result>
        </game>

        <game>
            <home>battle apples</home>
            <away>zzyzzx</away>
            <result>loss</result>
        </game>

        <game>
            <home>penguins</home>
            <away>phantoms</away>
            <result>loss</result>
        </game>
    </period>

		<!-- 10/11/2004 -->
    <period>
        <game>
            <home>zzyzzx</home>
            <away>penguins</away>
            <result>win</result>
        </game>

        <game>
            <home>battle apples</home>
            <away>buk hockey</away>
            <result>loss</result>
        </game>

        <game>
            <home>shockers</home>
            <away>spitfires</away>
            <result>loss</result>
        </game>

        <game>
            <home>space monkeys</home>
            <away>plug uglys</away>
            <result>win</result>
        </game>

        <game>
            <home>no ties</home>
            <away>phantoms</away>
            <result>loss</result>
        </game>
    </period>

		<!-- 10/25/2004 -->
    <period>
        <game>
            <home>battle apples</home>
            <away>plug uglys</away>
            <result>loss</result>
        </game>

        <game>
            <home>penguins</home>
            <away>shockers</away>
            <result>loss</result>
        </game>

        <game>
            <home>no ties</home>
            <away>spitfires</away>
            <result>win</result>
        </game>

        <game>
            <home>phantoms</home>
            <away>space monkeys</away>
            <result>draw</result>
        </game>

        <game>
            <home>zzyzzx</home>
            <away>buk hockey</away>
            <result>win</result>
        </game>
    </period>

		<!-- 11/01/2004 -->
    <period>
        <game>
            <home>phantoms</home>
            <away>buk hockey</away>
            <result>draw</result>
        </game>

        <game>
            <home>zzyzzx</home>
            <away>shockers</away>
            <result>win</result>
        </game>

        <game>
            <home>penguins</home>
            <away>plug uglys</away>
            <result>win</result>
        </game>

        <game>
            <home>no ties</home>
            <away>battle apples</away>
            <result>win</result>
        </game>

        <game>
            <home>spitfires</home>
            <away>space monkeys</away>
            <result>win</result>
        </game>
    </period>

		<!-- 11/15/2004 -->
    <period>
        <game>
            <home>shockers</home>
            <away>phantoms</away>
            <result>loss</result>
        </game>

        <game>
            <home>zzyzzx</home>
            <away>no ties</away>
            <result>win</result>
        </game>

        <game>
            <home>plug uglys</home>
            <away>buk hockey</away>
            <result>loss</result>
        </game>

        <game>
            <home>spitfires</home>
            <away>battle apples</away>
            <result>win</result>
        </game>

        <game>
            <home>space monkeys</home>
            <away>penguins</away>
            <result>win</result>
        </game>
    </period>

		<!-- 11/22/2004 -->
    <period>
        <game>
            <home>penguins</home>
            <away>spitfires</away>
            <result>loss</result>
        </game>

        <game>
            <home>buk hockey</home>
            <away>no ties</away>
            <result>win</result>
        </game>

        <game>
            <home>space monkeys</home>
            <away>zzyzzx</away>
            <result>win</result>
        </game>

        <game>
            <home>battle apples</home>
            <away>phantoms</away>
            <result>loss</result>
        </game>

        <game>
            <home>plug uglys</home>
            <away>shockers</away>
            <result>loss</result>
        </game>
    </period>

		<!-- 11/29/2004 -->
    <period>
        <game>
            <home>plug uglys</home>
            <away>spitfires</away>
            <result>loss</result>
        </game>

        <game>
            <home>phantoms</home>
            <away>zzyzzx</away>
            <result>win</result>
        </game>

        <game>
            <home>battle apples</home>
            <away>shockers</away>
            <result>win</result>
        </game>

        <game>
            <home>space monkeys</home>
            <away>no ties</away>
            <result>win</result>
        </game>

        <game>
            <home>buk hockey</home>
            <away>penguins</away>
            <result>loss</result>
        </game>
    </period>

		<!-- 12/06/2004 -->
    <period>
        <game>
            <home>space monkeys</home>
            <away>battle apples</away>
            <result>loss</result>
        </game>

        <game>
            <home>no ties</home>
            <away>penguins</away>
            <result>win</result>
        </game>

        <game>
            <home>buk hockey</home>
            <away>shockers</away>
            <result>win</result>
        </game>

        <game>
            <home>spitfires</home>
            <away>phantoms</away>
            <result>win</result>
        </game>

        <game>
            <home>plug uglys</home>
            <away>zzyzzx</away>
            <result>loss</result>
        </game>
    </period>

		<!-- 1/17/2005 -->
    <period>
        <game>
            <home>phantoms</home>
            <away>no ties</away>
            <result>win</result>
        </game>

        <game>
            <home>space monkeys</home>
            <away>buk hockey</away>
            <result>win</result>
        </game>

        <game>
            <home>spitfires</home>
            <away>battle apples</away>
            <result>win</result>
        </game>

        <game>
            <home>zzyzzx</home>
            <away>penguins</away>
            <result>loss</result>
        </game>
    </period>

</ratingdoc>
