=== swaits/glicko2/py/xmlrate.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="ratingtype">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="100.0"/>
        <xs:maxInclusive value="4000.0"/>
    </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="deviationtype">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="700.0"/>
    </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="volatilitytype">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="10.0"/>
    </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="nametype">
    <xs:restriction base="xs:string">
        <xs:whiteSpace value="collapse"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="commenttype">
    <xs:restriction base="xs:string">
        <xs:whiteSpace value="preserve"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="resulttype">
    <xs:restriction base ="xs:string">
        <xs:enumeration value="win"/>
        <xs:enumeration value="loss"/>
        <xs:enumeration value="draw"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="racetype">
    <xs:choice>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="competitor" type="nametype"/>
    </xs:choice>
</xs:complexType>

<xs:complexType name="gametype">
    <xs:all>
        <xs:element minOccurs="1" name="home" type="nametype"/>
        <xs:element minOccurs="1" name="away" type="nametype"/>
        <xs:element minOccurs="1" name="result" type="resulttype"/>
        <xs:element minOccurs="0" name="comment" type="commenttype"/>        
    </xs:all>
</xs:complexType>

<xs:complexType name="periodtype">
    <xs:choice>
        <xs:element maxOccurs="unbounded" name="game" type="gametype"/>
        <xs:element maxOccurs="unbounded" name="race" type="racetype"/>
    </xs:choice>
</xs:complexType>

<xs:complexType name="teamtype">
    <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" name="name" type="nametype"/>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="member" type="nametype"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="playertype">
    <xs:all>
        <xs:element minOccurs="1" name="name" type="nametype"/>
        <xs:element minOccurs="0" name="rating" type="ratingtype"/>
        <xs:element minOccurs="0" name="deviation" type="deviationtype"/>
        <xs:element minOccurs="0" name="volatility" type="volatilitytype"/>
    </xs:all>
</xs:complexType>

<xs:complexType name="ratingdoctype">
    <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="player" type="playertype"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="team" type="teamtype"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="period" type="periodtype"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="ratingdoc" type="ratingdoctype"/>

</xs:schema>

=== swaits/glicko2/py/data/hockey-2005.xml
<?xml version="1.0" encoding="UTF-8"?>

<ratingdoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.waits.net/XML/xmlrate.xsd">

	<player>
		<name>no ties</name>
		<rating>1472.6</rating>
		<deviation>100.3</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>zzyzzx</name>
		<rating>1657.5</rating>
		<deviation>106.0</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>penguins</name>
		<rating>1436.3</rating>
		<deviation>103.2</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>spitfires</name>
		<rating>1801.5</rating>
		<deviation>112.3</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>space monkeys</name>
		<rating>1659.8</rating>
		<deviation>98.1</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>plug uglys</name>
		<rating>1125.4</rating>
		<deviation>113.1</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>shockers</name>
		<rating>1196.3</rating>
		<deviation>117.0</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>phantoms</name>
		<rating>1652.6</rating>
		<deviation>98.6</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>battle apples</name>
		<rating>1302.6</rating>
		<deviation>156.9</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>blackouts</name>
		<rating>1531.3</rating>
		<deviation>121.4</deviation>
		<variance>0.06</variance>
	</player>

	<player>
		<name>coaches team</name>
	</player>

	<player>
		<name>old school</name>
	</player>

	<player>
		<name>ballistic</name>
	</player>

	<player>
		<name>velocity</name>
	</player>

	<player>
		<name>puckheads</name>
	</player>

	<player>
		<name>demons</name>
	</player>

	<player>
		<name>section 8</name>
	</player>

	<player>
		<name>who's your daddy</name>
	</player>

	<player>
		<name>blackhawks</name>
	</player>

	<player>
		<name>tiger sharks</name>
	</player>

	<period>
		<game>
			<home>phantoms</home>
			<away>spitfires</away>
			<result>loss</result>
		</game>
		<game>
			<home>battle apples</home>
			<away>blackouts</away>
			<result>loss</result>
		</game>
		<game>
			<home>zzyzzx</home>
			<away>penguins</away>
			<result>loss</result>
		</game>
		<game>
			<home>plug uglys</home>
			<away>space monkeys</away>
			<result>loss</result>
		</game>
		<game>
			<home>no ties</home>
			<away>coaches team</away>
			<result>win</result>
		</game>
	</period>

	<period>
		<game>
			<home>spitfires</home>
			<away>no ties</away>
			<result>draw</result>
		</game>
		<game>
			<home>penguins</home>
			<away>blackouts</away>
			<result>win</result>
		</game>
		<game>
			<home>zzyzzx</home>
			<away>plug uglys</away>
			<result>win</result>
		</game>
		<game>
			<home>space monkeys</home>
			<away>old school</away>
			<result>win</result>
		</game>
		<game>
			<home>coaches team</home>
			<away>shockers</away>
			<result>win</result>
		</game>
		<game>
			<home>phantoms</home>
			<away>battle apples</away>
			<result>win</result>
		</game>
	</period>

	<period>
		<game>
			<home>space monkeys</home>
			<away>zzyzzx</away>
			<result>win</result>
		</game>
		<game>
			<home>coaches team</home>
			<away>battle apples</away>
			<result>win</result>
		</game>
		<game>
			<home>plug uglys</home>
			<away>phantoms</away>
			<result>loss</result>
		</game>
		<game>
			<home>shockers</home>
			<away>spitfires</away>
			<result>loss</result>
		</game>
		<game>
			<home>blackouts</home>
			<away>old school</away>
			<result>win</result>
		</game>
		<game>
			<home>no ties</home>
			<away>penguins</away>
			<result>loss</result>
		</game>
	</period>

	<period>
		<game>
			<home>old school</home>
			<away>phantoms</away>
			<result>loss</result>
		</game>
		<game>
			<home>plug uglys</home>
			<away>no ties</away>
			<result>loss</result>
		</game>
		<game>
			<home>shockers</home>
			<away>zzyzzx</away>
			<result>loss</result>
		</game>
		<game>
			<home>blackouts</home>
			<away>space monkeys</away>
			<result>win</result>
		</game>
		<game>
			<home>coaches team</home>
			<away>penguins</away>
			<result>loss</result>
		</game>
		<game>
			<home>spitfires</home>
			<away>battle apples</away>
			<result>win</result>
		</game>
	</period>

	<period>
		<game>
			<home>battle apples</home>
			<away>shockers</away>
			<result>loss</result>
		</game>
		<game>
			<home>zzyzzx</home>
			<away>blackouts</away>
			<result>win</result>
		</game>
		<game>
			<home>space monkeys</home>
			<away>phantoms</away>
			<result>loss</result>
		</game>
		<game>
			<home>no ties</home>
			<away>old school</away>
			<result>win</result>
		</game>
		<game>
			<home>penguins</home>
			<away>spitfires</away>
			<result>loss</result>
		</game>
		<game>
			<home>coaches team</home>
			<away>plug uglys</away>
			<result>win</result>
		</game>
	</period>

	<period>
		<game>
			<home>no ties</home>
			<away>space monkeys</away>
			<result>win</result>
		</game>
		<game>
			<home>old school</home>
			<away>coaches team</away>
			<result>win</result>
		</game>
		<game>
			<home>penguins</home>
			<away>battle apples</away>
			<result>win</result>
		</game>
		<game>
			<home>plug uglys</home>
			<away>spitfires</away>
			<result>draw</result>
		</game>
		<game>
			<home>phantoms</home>
			<away>zzyzzx</away>
			<result>loss</result>
		</game>
		<game>
			<home>shockers</home>
			<away>blackouts</away>
			<result>win</result>
		</game>
	</period>

	<period>
		<game>
			<home>blackouts</home>
			<away>phantoms</away>
			<result>loss</result>
		</game>
		<game>
			<home>penguins</home>
			<away>shockers</away>
			<result>win</result>
		</game>
		<game>
			<home>zzyzzx</home>
			<away>no ties</away>
			<result>win</result>
		</game>
		<game>
			<home>space monkeys</home>
			<away>coaches team</away>
			<result>loss</result>
		</game>
		<game>
			<home>battle apples</home>
			<away>plug uglys</away>
			<result>loss</result>
		</game>
		<game>
			<home>spitfires</home>
			<away>old school</away>
			<result>win</result>
		</game>
	</period>

	<period>
		<game>
			<home>phantoms</home>
			<away>shockers</away>
			<result>win</result>
		</game>
		<game>
			<home>blackouts</home>
			<away>no ties</away>
			<result>loss</result>
		</game>
		<game>
			<home>battle apples</home>
			<away>old school</away>
			<result>win</result>
		</game>
		<game>
			<home>plug uglys</home>
			<away>penguins</away>
			<result>loss</result>
		</game>
		<game>
			<home>space monkeys</home>
			<away>spitfires</away>
			<result>draw</result>
		</game>
		<game>
			<home>zzyzzx</home>
			<away>coaches team</away>
			<result>win</result>
		</game>
	</period>

	<period>
		<game>
			<home>spitfires</home>
			<away>zzyzzx</away>
			<result>loss</result>
		</game>
		<game>
			<home>space monkeys</home>
			<away>battle apples</away>
			<result>win</result>
		</game>
		<game>
			<home>no ties</home>
			<away>phantoms</away>
			<result>loss</result>
		</game>
		<game>
			<home>coaches team</home>
			<away>blackouts</away>
			<result>loss</result>
		</game>
		<game>
			<home>shockers</home>
			<away>plug uglys</away>
			<result>loss</result>
		</game>
		<game>
			<home>old school</home>
			<away>penguins</away>
			<result>loss</result>
		</game>
	</period>

	<period>
		<game>
			<home>old school</home>
			<away>shockers</away>
			<result>win</result>
		</game>
	</period>

	<!-- mon, 4/25 -->
	<period>
		<game>
			<home>spitfires</home>
			<away>coaches team</away>
			<result>win</result>
		</game>
		<game>
			<home>battle apples</home>
			<away>no ties</away>
			<result>loss</result>
		</game>
		<game>
			<home>old school</home>
			<away>zzyzzx</away>
			<result>loss</result>
		</game>
		<game>
			<home>penguins</home>
			<away>phantoms</away>
			<result>loss</result>
		</game>
		<game>
			<home>blackouts</home>
			<away>plug uglys</away>
			<result>win</result>
		</game>
		<game>
			<home>shockers</home>
			<away>space monkeys</away>
			<result>loss</result>
		</game>
	</period>

	<!-- wed, 4/27 -->
	<period>
		<game>
			<home>shockers</home>
			<away>ballistic</away>
			<result>loss</result>
		</game>
		<game>
			<home>blackhawks</home>
			<away>puckheads</away>
			<result>win</result>
		</game>
		<game>
			<home>section 8</home>
			<away>velocity</away>
			<result>draw</result>
		</game>
		<game>
			<home>demons</home>
			<away>spitfires</away>
			<result>draw</result>
		</game>
		<game>
			<home>who's your daddy</home>
			<away>tiger sharks</away>
			<result>draw</result>
		</game>
	</period>

    <!-- mon, 5/2 (playoffs round 1) -->
    <period>
        <game>
            <home>no ties</home>
            <away>penguins</away>
            <result>loss</result>
        </game>
        <game>
            <home>phantoms</home>
            <away>space monkeys</away>
            <result>loss</result>
        </game>
        <game>
            <home>zzyzzx</home>
            <away>coaches team</away>
            <result>loss</result>
        </game>
        <game>
            <home>spitfires</home>
            <away>blackouts</away>
            <result>win</result>
        </game>
    </period>

    <!-- wed 5/11 -->
    <period>
        <game>
            <home>velocity</home>
            <away>shockers</away>
            <result>win</result>
        </game>
        <game>
            <home>who's your daddy</home>
            <away>demons</away>
            <result>win</result>
        </game>
        <game>
            <home>ballistic</home>
            <away>puckheads</away>
            <result>win</result>
        </game>
        <game>
            <home>section 8</home>
            <away>blackhawks</away>
            <result>loss</result>
        </game>
        <game>
            <home>spitfires</home>
            <away>tiger sharks</away>
            <result>win</result>
        </game>
    </period>

</ratingdoc>

=== swaits/glicko2/py/example.xml
<?xml version="1.0" encoding="UTF-8"?>

<ratingdoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.waits.net/XML/xmlrate.xsd">


    <player>
        <name>A</name>
        <rating>1500</rating>
        <deviation>200</deviation>
        <volatility>0.06</volatility>
    </player>

    <player>
        <name>B</name>
        <rating>1400</rating>
        <deviation>30</deviation>
        <volatility>0.06</volatility>
    </player>

    <player>
        <name>C</name>
        <rating>1550</rating>
        <deviation>100</deviation>
        <volatility>0.06</volatility>
    </player>

    <player>
        <name>D</name>
        <rating>1700</rating>
        <deviation>300</deviation>
        <volatility>0.06</volatility>
    </player>


    <period>
        <game>
            <home>A</home>
            <away>B</away>
            <result>win</result>
        </game>

        <game>
            <home>A</home>
            <away>C</away>
            <result>loss</result>
        </game>

        <game>
            <home>A</home>
            <away>D</away>
            <result>loss</result>
        </game>
    </period>

</ratingdoc>

=== swaits/glicko2/py/data/hockey-1.xml
<?xml version="1.0" encoding="UTF-8"?>

<ratingdoc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.waits.net/XML/xmlrate.xsd">

    <player>
        <name>penguins</name>
    </player>

    <player>
        <name>no ties</name>
    </player>

    <player>
        <name>zzyzzx</name>
    </player>

    <player>
        <name>spitfires</name>
    </player>

    <player>
        <name>red liners</name>
    </player>

    <player>
        <name>space monkeys</name>
    </player>

    <player>
        <name>phantoms</name>
    </player>

    <player>
        <name>jinx</name>
    </player>

    <player>
        <name>plug uglys</name>
    </player>

    <player>
        <name>shockers</name>
    </player>


    <period>
        <game>
            <home>jinx</home>
            <away>space monkeys</away>
            <result>win</result>
        </game>

        <game>
            <home>zzyzzx</home>
            <away>no ties</away>
            <result>loss</result>
        </game>

        <game>
            <home>plug uglys</home>
            <away>red liners</away>
            <result>loss</result>
        </game>

        <game>
            <home>phantoms</home>
            <away>penguins</away>
            <result>loss</result>
        </game>
    </period>

    <period>
        <game>
            <home>no ties</home>
            <away>spitfires</away>
            <result>loss</result>
        </game>

        <game>
            <home>jinx</home>
            <away>phantoms</away>
            <result>loss</result>
        </game>

        <game>
            <home>space monkeys</home>
            <away>shockers</away>
            <result>win</result>
        </game>

        <game>
            <home>zzyzzx</home>
            <away>plug uglys</away>
            <result>win</result>
        </game>

        <game>
            <home>penguins</home>
            <away>red liners</away>
            <result>win</result>
        </game>
    </period>

    <period>
        <game>
            <home>penguins</home>
            <away>zzyzzx</away>
            <result>loss</result>
        </game>

        <game>
            <home>spitfires</home>
            <away>plug uglys</away>
            <result>win</result>
        </game>

        <game>
            <home>no ties</home>
            <away>shockers</away>
            <result>win</result>
        </game>

        <game>
            <home>red liners</home>
            <away>jinx</away>
            <result>win</result>
        </game>

        <game>
            <home>space monkeys</home>
            <away>phantoms</away>
            <result>draw</result>
        </game>
    </period>

		<period>

			<game>
				<home>jinx</home>
				<away>zzyzzx</away>
				<result>loss</result>
			</game>

			<game>
				<home>red liners</home>
				<away>space monkeys</away>
				<result>loss</result>
			</game>

			<game>
				<home>plug uglys</home>
				<away>no ties</away>
				<result>loss</result>
			</game>

			<game>
				<home>spitfires</home>
				<away>penguins</away>
				<result>win</result>
			</game>

			<game>
				<home>phantoms</home>
				<away>shockers</away>
				<result>win</result>
			</game>

		</period>

		<period>

			<game>
				<home>shockers</home>
				<away>plug uglys</away>
				<result>draw</result>
			</game>

			<game>
				<home>spitfires</home>
				<away>jinx</away>
				<result>win</result>
			</game>

			<game>
				<home>penguins</home>
				<away>no ties</away>
				<result>loss</result>
			</game>

			<game>
				<home>red liners</home>
				<away>phantoms</away>
				<result>win</result>
			</game>

			<game>
				<home>space monkeys</home>
				<away>zzyzzx</away>
				<result>loss</result>
			</game>

		</period>

		<period> <!-- July 26th -->

			<game>
				<home>plug uglys</home>
				<away>penguins</away>
				<result>draw</result>
			</game>

			<game>
				<home>spitfires</home>
				<away>space monkeys</away>
				<result>draw</result>
			</game>

			<game>
				<home>shockers</home>
				<away>red liners</away>
				<result>loss</result>
			</game>

			<game>
				<home>phantoms</home>
				<away>zzyzzx</away>
				<result>loss</result>
			</game>

			<game>
				<home>no ties</home>
				<away>jinx</away>
				<result>loss</result>
			</game>

		</period>

		<period> <!-- August 2nd -->

			<game>
				<home>phantoms</home>
				<away>spitfires</away>
				<result>loss</result>
			</game>

			<game>
				<home>plug uglys</home>
				<away>jinx</away>
				<result>win</result>
			</game>

			<game>
				<home>no ties</home>
				<away>space monkeys</away>
				<result>loss</result>
			</game>

			<game>
				<home>shockers</home>
				<away>penguins</away>
				<result>loss</result>
			</game>

			<game>
				<home>zzyzzx</home>
				<away>red liners</away>
				<result>loss</result>
			</game>

		</period>

		<period> <!-- August 9th -->

			<game>
				<home>space monkeys</home>
				<away>plug uglys</away>
				<result>win</result>
			</game>

			<game>
				<home>penguins</home>
				<away>jinx</away>
				<result>win</result>
			</game>

			<game>
				<home>red liners</home>
				<away>spitfires</away>
				<result>loss</result>
			</game>

			<game>
				<home>zzyzzx</home>
				<away>shockers</away>
				<result>win</result>
			</game>

			<game>
				<home>phantoms</home>
				<away>no ties</away>
				<result>draw</result>
			</game>

		</period>

		<period> <!-- August 16th -->

			<game>
				<home>red liners</home>
				<away>no ties</away>
				<result>win</result>
			</game>

			<game>
				<home>zzyzzx</home>
				<away>spitfires</away>
				<result>win</result> <!-- upset! -->
			</game>

			<game>
				<home>space monkeys</home>
				<away>penguins</away>
				<result>win</result>
			</game>

			<game>
				<home>plug uglys</home>
				<away>phantoms</away>
				<result>loss</result>
			</game>

			<game>
				<home>jinx</home>
				<away>shockers</away>
				<result>draw</result>
			</game>

		</period>

		<period> <!-- August 23rd -->

			<game>
				<home>spitfires</home>
				<away>shockers</away>
				<result>win</result>
			</game>

			<game>
				<home>no ties</home>
				<away>zzyzzx</away>
				<result>draw</result>
			</game>

			<game>
				<home>space monkeys</home>
				<away>jinx</away>
				<result>win</result>
			</game>

			<game>
				<home>red liners</home>
				<away>plug uglys</away>
				<result>win</result>
			</game>

		</period>

		<period> <!-- August 30th -->

			<game>
				<home>spitfires</home>
				<away>shockers</away>
				<result>win</result>
			</game>

		</period>

		<period> <!-- Sep 13th -->

			<game>
				<home>red liners</home>
				<away>phantoms</away>
				<result>win</result>
			</game>

			<game>
				<home>red liners</home>
				<away>space monkeys</away>
				<result>win</result>
			</game>

			<game>
				<home>spitfires</home>
				<away>phantoms</away>
				<result>loss</result>
			</game>

			<!-- other games unknown!!! -->

		</period>

</ratingdoc>
